<?php

namespace Casadatos\Component\Dashboard\Gauge;

class PercentGauge extends ValueGauge
{
    private $length;

    public function __construct($length=10,  $format = "%s", $pad = STR_PAD_LEFT)
    {
        $this->length = $length;

        parent::__construct($length - 1, $format, $pad);
    }

    public function getLength()
    {
        return $this->length;
    }

    public function refresh($force=false)
    {
        return parent::refresh($force) . '%'; // TODO: Change the autogenerated stub
    }
}
